organization := "com.streetcontxt"
name := "jooq-scala-macro"
description := "A public type provider macro which produces a set of objects and classes based on those generated by Jooq"
licenses += ("Apache-2.0", url("http://www.apache.org/licenses/LICENSE-2.0.html"))
homepage := Some(url("https://github.com/StreetContxt/jooq-scala-macro"))

bintrayOrganization := Some("streetcontxt")
resolvers += Resolver.bintrayRepo("streetcontxt", "maven")
resolvers += Resolver.mavenLocal

scalaVersion := "2.12.7"
crossScalaVersions := Seq("2.11.12", "2.12.7")

val versionPattern = "release-([0-9\\.]*)".r
version := sys.props
  .get("CIRCLE_TAG")
  .orElse(sys.env.get("CIRCLE_TAG"))
  .flatMap {
    case versionPattern(v) => Some(v)
    case _ => None
  }
  .getOrElse("LOCAL-SNAPSHOT")

scalacOptions ++= Seq(
  "-deprecation",
  "-feature",
  "-unchecked",
  "-Ymacro-debug-lite",
  "-Xlint"
)

lazy val paradiseDependency = "org.scalamacros" % "paradise" % "2.1.0" cross CrossVersion.full
addCompilerPlugin(paradiseDependency)

libraryDependencies ++= Seq(
  "org.jooq" % "jooq" % "3.11.4",
  "org.jooq" %% "jooq-scala" % "3.10.2",
  "org.scala-lang" % "scala-reflect" % scalaVersion.value,
  paradiseDependency
)
