version: 2

references:
  defaults: &defaults
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
  restoreCache: &restoreCache
    key: v1-dependencies-{{ checksum "build.sbt" }}-{{ checksum "project/plugins.sbt" }}
  saveCache: &saveCache
    paths: ["~/.ivy2", "~/.sbt"]
    key: v1-dependencies-{{ checksum "build.sbt" }}-{{ checksum "project/plugins.sbt" }}

jobs:
  build_and_test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          <<: *restoreCache
      - run: sbt +test +package < /dev/null
      - save_cache:
          <<: *saveCache
      - persist_to_workspace:
          root: ..
          paths:
            - repo
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/circleci
      - restore_cache:
          <<: *restoreCache
      - run: sbt +publish < /dev/null

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - deploy:
          requires:
            - build_and_test
          filters:
            tags:
              only: /^release-(.+)$/
            branches:
              ignore: /.*/
