/*
 * This file is generated by jOOQ.
*/
package com.contxt.jooq.test;


import com.contxt.jooq.test.tables.Author;
import com.contxt.jooq.test.tables.Book;
import com.contxt.jooq.test.tables.BookStore;
import com.contxt.jooq.test.tables.BookToBookStore;
import com.contxt.jooq.test.tables.Language;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling indexes of tables of the <code>TEST</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRIMARY_KEY_7 = Indexes0.PRIMARY_KEY_7;
    public static final Index FK_BOOK_AUTHOR_INDEX_1 = Indexes0.FK_BOOK_AUTHOR_INDEX_1;
    public static final Index FK_BOOK_LANGUAGE_INDEX_1 = Indexes0.FK_BOOK_LANGUAGE_INDEX_1;
    public static final Index PRIMARY_KEY_1 = Indexes0.PRIMARY_KEY_1;
    public static final Index CONSTRAINT_INDEX_F = Indexes0.CONSTRAINT_INDEX_F;
    public static final Index FK_B2BS_BOOK_INDEX_2 = Indexes0.FK_B2BS_BOOK_INDEX_2;
    public static final Index PRIMARY_KEY_2 = Indexes0.PRIMARY_KEY_2;
    public static final Index PRIMARY_KEY_C = Indexes0.PRIMARY_KEY_C;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index PRIMARY_KEY_7 = createIndex("PRIMARY_KEY_7", Author.AUTHOR, new OrderField[] { Author.AUTHOR.ID }, true);
        public static Index FK_BOOK_AUTHOR_INDEX_1 = createIndex("FK_BOOK_AUTHOR_INDEX_1", Book.BOOK, new OrderField[] { Book.BOOK.AUTHOR_ID }, false);
        public static Index FK_BOOK_LANGUAGE_INDEX_1 = createIndex("FK_BOOK_LANGUAGE_INDEX_1", Book.BOOK, new OrderField[] { Book.BOOK.LANGUAGE_ID }, false);
        public static Index PRIMARY_KEY_1 = createIndex("PRIMARY_KEY_1", Book.BOOK, new OrderField[] { Book.BOOK.ID }, true);
        public static Index CONSTRAINT_INDEX_F = createIndex("CONSTRAINT_INDEX_F", BookStore.BOOK_STORE, new OrderField[] { BookStore.BOOK_STORE.NAME }, true);
        public static Index FK_B2BS_BOOK_INDEX_2 = createIndex("FK_B2BS_BOOK_INDEX_2", BookToBookStore.BOOK_TO_BOOK_STORE, new OrderField[] { BookToBookStore.BOOK_TO_BOOK_STORE.BOOK_ID }, false);
        public static Index PRIMARY_KEY_2 = createIndex("PRIMARY_KEY_2", BookToBookStore.BOOK_TO_BOOK_STORE, new OrderField[] { BookToBookStore.BOOK_TO_BOOK_STORE.NAME, BookToBookStore.BOOK_TO_BOOK_STORE.BOOK_ID }, true);
        public static Index PRIMARY_KEY_C = createIndex("PRIMARY_KEY_C", Language.LANGUAGE, new OrderField[] { Language.LANGUAGE.ID }, true);
    }
}
