/*
 * This file is generated by jOOQ.
*/
package com.contxt.jooq.test;


import com.contxt.jooq.test.tables.Author;
import com.contxt.jooq.test.tables.Book;
import com.contxt.jooq.test.tables.BookStore;
import com.contxt.jooq.test.tables.BookToBookStore;
import com.contxt.jooq.test.tables.Language;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in TEST
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>TEST.AUTHOR</code>.
     */
    public static final Author AUTHOR = com.contxt.jooq.test.tables.Author.AUTHOR;

    /**
     * The table <code>TEST.BOOK</code>.
     */
    public static final Book BOOK = com.contxt.jooq.test.tables.Book.BOOK;

    /**
     * The table <code>TEST.BOOK_STORE</code>.
     */
    public static final BookStore BOOK_STORE = com.contxt.jooq.test.tables.BookStore.BOOK_STORE;

    /**
     * The table <code>TEST.BOOK_TO_BOOK_STORE</code>.
     */
    public static final BookToBookStore BOOK_TO_BOOK_STORE = com.contxt.jooq.test.tables.BookToBookStore.BOOK_TO_BOOK_STORE;

    /**
     * The table <code>TEST.LANGUAGE</code>.
     */
    public static final Language LANGUAGE = com.contxt.jooq.test.tables.Language.LANGUAGE;
}
