/*
 * This file is generated by jOOQ.
*/
package com.contxt.jooq.test;


import com.contxt.jooq.DefaultCatalog;
import com.contxt.jooq.test.tables.Author;
import com.contxt.jooq.test.tables.Book;
import com.contxt.jooq.test.tables.BookStore;
import com.contxt.jooq.test.tables.BookToBookStore;
import com.contxt.jooq.test.tables.Language;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test extends SchemaImpl {

    private static final long serialVersionUID = 203876022;

    /**
     * The reference instance of <code>TEST</code>
     */
    public static final Test TEST = new Test();

    /**
     * The table <code>TEST.AUTHOR</code>.
     */
    public final Author AUTHOR = com.contxt.jooq.test.tables.Author.AUTHOR;

    /**
     * The table <code>TEST.BOOK</code>.
     */
    public final Book BOOK = com.contxt.jooq.test.tables.Book.BOOK;

    /**
     * The table <code>TEST.BOOK_STORE</code>.
     */
    public final BookStore BOOK_STORE = com.contxt.jooq.test.tables.BookStore.BOOK_STORE;

    /**
     * The table <code>TEST.BOOK_TO_BOOK_STORE</code>.
     */
    public final BookToBookStore BOOK_TO_BOOK_STORE = com.contxt.jooq.test.tables.BookToBookStore.BOOK_TO_BOOK_STORE;

    /**
     * The table <code>TEST.LANGUAGE</code>.
     */
    public final Language LANGUAGE = com.contxt.jooq.test.tables.Language.LANGUAGE;

    /**
     * No further instances allowed
     */
    private Test() {
        super("TEST", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Author.AUTHOR,
            Book.BOOK,
            BookStore.BOOK_STORE,
            BookToBookStore.BOOK_TO_BOOK_STORE,
            Language.LANGUAGE);
    }
}
